export const DEFAULT_SUBTOPIC_EXPLORATIONS: Record<string, string[]> = {
    Physics: [
        'Mechanics & dynamical systems',
        'Energy, symmetry & conservation',
        'Waves & oscillations',
        'Thermal & statistical physics',
        'Electromagnetism',
        'Classical & quantum fields',
        'Relativity & gravitation',
        'Quantum theory',
        'Matter & condensed matter',
        'Nuclear, particle & fundamental physics',
    ],
    'Mathematics & Logic': [
        'Numbers & arithmetic structures',
        'Equations & functions',
        'Algebraic structures',
        'Geometry & space',
        'Calculus & continuous change',
        'Probability',
        'Statistics',
        'Linear algebra',
        'Discrete structures & combinatorics',
        'Logic & proof',
    ],
    Chemistry: [
        'Atomic & electronic structure',
        'Bonding & molecular structure',
        'Chemical thermodynamics',
        'Kinetics & reaction mechanisms',
        'Equilibrium & solution chemistry',
        'Electrochemistry & redox',
        'Organic chemistry & synthesis',
        'Inorganic & coordination chemistry',
        'Spectroscopy & analytical chemistry',
        'Materials & supramolecular chemistry',
    ],
    Life: [
        'Molecular & cellular biology',
        'Genetics & genomics',
        'Metabolism & bioenergetics',
        'Regulation & cellular signaling',
        'Development & reproduction',
        'Physiology & homeostasis',
        'Neuroscience',
        'Evolution & population genetics',
        'Ecology & ecosystems',
        'Systems biology & adaptation',
    ],
    'Computer Science': [
        'Algorithms & data structures',
        'Automata, formal languages & computability',
        'Complexity theory',
        'Programming languages & compilers',
        'Computer architecture',
        'Operating systems & systems programming',
        'Networks & communication',
        'Databases & information systems',
        'Distributed & concurrent systems',
        'Artificial intelligence & machine learning',
        'Cryptography & security',
        'Graphics, vision & multimedia',
    ],
    'Earth & Space': [
        'Geophysics & Earth\'s interior',
        'Tectonics & geological dynamics',
        'Geochemistry & Earth history',
        'Atmospheric science & weather',
        'Climate science',
        'Ocean & hydrological systems',
        'Planetary science',
        'Stellar astrophysics',
        'Galaxies & high-energy astrophysics',
        'Cosmology & the universe',
    ],
    'Mind & Behavior': [
        'Perception & sensory processing',
        'Attention & cognitive control',
        'Learning & memory',
        'Reasoning & decision-making',
        'Emotion & motivation',
        'Language & cognition',
        'Social cognition & behavior',
        'Development & individual differences',
        'Brain & cognition',
        'Consciousness & philosophy of mind',
    ],
    'Society & History': [
        'Ancient societies & civilizations',
        'States, institutions & governance',
        'Economic systems & trade',
        'Religion, ideology & culture',
        'War, power & geopolitics',
        'Social structures & demographic change',
        'Revolutions & political transformation',
        'Technology, industry & modernization',
        'Empires, colonialism & globalization',
        'International systems & the modern world',
    ],
};
