/** Scripted transfer, counterfactual and evidence challenges for the Life preview. */
export type AdvancedSample = [question: string, correct: string, wrong1: string, wrong2: string, wrong3: string];
export const lifeAdvanced: Record<string, AdvancedSample[]> = {
    'food-fuel': [
        ['A seedling grows in a dark cupboard and its stored materials decrease. Which account explains both observations?', 'Stored materials supply building blocks and chemical energy for growth.', 'Darkness supplies both matter and energy.', 'Growth creates matter and energy from nothing.', 'A decrease in stores proves the seedling is not growing.'],
        ['An animal has plenty of food inside it but cannot transfer energy from that food into its activities. Would adding more of the same food necessarily restore activity?', 'No. An abundant supply does not fix the inability to use its energy.', 'Yes. Food quantity is the only condition that matters.', 'Yes. Food automatically pushes muscles without being processed.', 'No. Food never supplies energy for activity.'],
        ['Two explanations predict that an animal can move between meals: stored fuel is used, or movement creates its own fuel. Which measurement best distinguishes them?', 'Track use of stored materials alongside activity and energy transfer.', 'Record only whether the animal moves once.', 'Measure the color of the animal’s surroundings.', 'Count meals without observing stored materials or activity.'],
    ],
    cells: [
        ['A sheet of living tissue is folded so tightly that its inner cells receive fewer supplies. Why might those cells function less well even though the whole sheet is intact?', 'Individual cells still need material exchange across their own boundaries.', 'An intact sheet guarantees unlimited supplies to every cell.', 'Only cells on the outside require any materials.', 'Folding turns cells into nonliving empty spaces.'],
        ['Suppose a cell boundary blocked every substance while the cell kept working. Which consequence follows from the cell’s need to exchange materials?', 'Supplies could run down and waste could accumulate inside.', 'The boundary would create whatever matter was missing.', 'Blocking exchange would remove all need for energy.', 'Every process could continue forever with no change.'],
        ['Two microscope samples show different cell shapes. Someone concludes that only one type needs supplies. What would test that conclusion?', 'Measure material uptake and waste release in both living cell types.', 'Compare shapes again without measuring exchange.', 'Choose the larger cells as the only living ones.', 'Assume a shared need requires identical appearance.'],
    ],
    stores: [
        ['A reserve starts with 20 units. For three hours, 2 units enter and 5 leave each hour. What remains?', '11 units: the reserve loses 3 units per hour.', '29 units: all incoming units increase the reserve.', '5 units: ignore the incoming supply.', '20 units: a reserve always stays at its starting level.'],
        ['A reserve receives and supplies 4 units per hour. Its contents stay constant. If incoming supply stops while use continues, what changes?', 'The previously steady reserve begins to fall by 4 units per hour.', 'It stays constant because it was steady before.', 'It immediately becomes an unlimited reserve.', 'It rises because one of the flows stopped.'],
        ['A store has the same amount at two measurements. Does that prove no fuel entered or left?', 'No. Equal total inflow and outflow could leave the amount unchanged.', 'Yes. An unchanged amount proves both flows were zero.', 'Yes. Stored material cannot be replaced over time.', 'No. The amount must have doubled between measurements.'],
    ],
    feedback: [
        ['A greenhouse cools, its heater starts, and heating decreases as temperature recovers. Which relationship must work for this response to adjust to a second cold spell?', 'Temperature information must influence the heating response again.', 'The first response must keep heating at maximum forever.', 'The sensor must create all the heat without an energy supply.', 'The heater must ignore conditions after its first response.'],
        ['A tank controller detects low water correctly but its inlet valve is stuck closed. Why might the level keep falling?', 'Detecting the change is insufficient when the corrective action cannot occur.', 'Correct detection guarantees a restored level regardless of the valve.', 'The sensor replaces the need for incoming water.', 'Negative feedback means all changes are reinforced.'],
        ['A heater runs every evening. How could you test whether temperature, rather than only a timer, controls it?', 'Vary temperature at the same clock time and compare its response.', 'Observe it once at the usual evening temperature.', 'Check that its outer case is labeled automatic.', 'Change both time and temperature together without recording either.'],
    ],
};
