import { Question, ChatMessage } from '../../types';
import {
  QUESTION_SYSTEM_PROMPT,
  getQuestionUserPrompt,
  getChatSystemPrompt,
  extractJsonFromResponse,
} from './prompt';

interface AnthropicContentBlock {
  type: string;
  text?: string;
}

interface AnthropicResponse {
  content?: AnthropicContentBlock[];
  error?: {
    type: string;
    message: string;
  };
}

export async function generateAnthropicQuestion(
  model: string,
  apiKey: string,
  topics: string[],
  specificTopic?: string,
  recentQuestions?: string[]
): Promise<Question> {
  const chosenTopic = specificTopic || topics[Math.floor(Math.random() * topics.length)] || 'Physics';
  const userPrompt = getQuestionUserPrompt(topics, chosenTopic, recentQuestions);

  const response = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'x-api-key': apiKey,
      'anthropic-version': '2023-06-01',
      'anthropic-dangerous-direct-browser-access': 'true',
    },
    body: JSON.stringify({
      model: model || 'claude-3-7-sonnet-20250219',
      system: QUESTION_SYSTEM_PROMPT,
      messages: [{ role: 'user', content: userPrompt }],
      max_tokens: 1024,
      temperature: 0.95,
    }),
  });

  if (!response.ok) {
    const errData = await response.json().catch(() => ({}));
    const message = (errData as AnthropicResponse)?.error?.message || response.statusText;
    throw new Error(`Anthropic API Error (${response.status}): ${message}`);
  }

  const data: AnthropicResponse = await response.json();
  const text = data.content?.[0]?.text;

  if (!text) {
    throw new Error('Anthropic returned an empty response. Please try again.');
  }

  interface ParsedQuestion {
    topic?: string;
    question?: string;
    options?: string[];
    correctIndex?: number;
    explanation?: string;
  }

  const parsed = extractJsonFromResponse<ParsedQuestion>(text);

  if (!parsed.question || !Array.isArray(parsed.options) || parsed.options.length !== 4) {
    throw new Error('Malformed question generated by Anthropic. Please try again.');
  }

  return {
    topic: parsed.topic || chosenTopic,
    questionText: parsed.question,
    options: parsed.options,
    correctIndex: typeof parsed.correctIndex === 'number' ? parsed.correctIndex : 0,
    explanation: parsed.explanation || 'No explanation provided.',
  };
}

export async function chatWithAnthropic(
  model: string,
  apiKey: string,
  context: Question,
  history: ChatMessage[],
  newMessage: string
): Promise<string> {
  const messages = [
    ...history.map((msg) => ({
      role: msg.role === 'user' ? ('user' as const) : ('assistant' as const),
      content: msg.content,
    })),
    { role: 'user' as const, content: newMessage },
  ];

  const response = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'x-api-key': apiKey,
      'anthropic-version': '2023-06-01',
      'anthropic-dangerous-direct-browser-access': 'true',
    },
    body: JSON.stringify({
      model: model || 'claude-3-5-sonnet-20241022',
      system: getChatSystemPrompt(context),
      messages,
      max_tokens: 1024,
      temperature: 0.7,
    }),
  });

  if (!response.ok) {
    const errData = await response.json().catch(() => ({}));
    const message = (errData as AnthropicResponse)?.error?.message || response.statusText;
    throw new Error(`Anthropic Chat Error (${response.status}): ${message}`);
  }

  const data: AnthropicResponse = await response.json();
  const text = data.content?.[0]?.text;

  if (!text) {
    throw new Error('Anthropic returned an empty reply.');
  }

  return text;
}

export async function testAnthropicKey(model: string, apiKey: string): Promise<{ success: boolean; message: string }> {
  try {
    const response = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': apiKey,
        'anthropic-version': '2023-06-01',
        'anthropic-dangerous-direct-browser-access': 'true',
      },
      body: JSON.stringify({
        model: model || 'claude-3-5-haiku-20241022',
        messages: [{ role: 'user', content: 'Ping! Reply with "OK".' }],
        max_tokens: 10,
      }),
    });

    if (!response.ok) {
      const errData = await response.json().catch(() => ({}));
      const message = (errData as AnthropicResponse)?.error?.message || response.statusText;
      return { success: false, message: `Failed (${response.status}): ${message}` };
    }

    return { success: true, message: 'Successfully connected to Anthropic Claude API!' };
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err);
    return { success: false, message: `Connection error: ${message}` };
  }
}
