import { Question, ChatMessage } from '../../types';
import {
  QUESTION_SYSTEM_PROMPT,
  getQuestionUserPrompt,
  getChatSystemPrompt,
  extractJsonFromResponse,
} from './prompt';

interface GeminiResponse {
  candidates?: Array<{
    content?: {
      parts?: Array<{
        text?: string;
      }>;
    };
    finishReason?: string;
  }>;
  error?: {
    code: number;
    message: string;
    status: string;
  };
}

export async function generateGeminiQuestion(
  model: string,
  apiKey: string,
  topics: string[],
  specificTopic?: string,
  recentQuestions?: string[],
  customSubtopics?: string[]
): Promise<Question> {
  const chosenTopic = specificTopic || topics[Math.floor(Math.random() * topics.length)] || 'Physics';
  const userPrompt = getQuestionUserPrompt(topics, chosenTopic, recentQuestions, customSubtopics);

  const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`;

  const response = await fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      contents: [
        {
          role: 'user',
          parts: [{ text: userPrompt }],
        },
      ],
      systemInstruction: {
        parts: [{ text: QUESTION_SYSTEM_PROMPT }],
      },
      generationConfig: {
        temperature: 0.95,
        responseMimeType: 'application/json',
      },
    }),
  });

  if (!response.ok) {
    const errData = await response.json().catch(() => ({}));
    const message = (errData as GeminiResponse)?.error?.message || response.statusText;
    throw new Error(`Gemini API Error (${response.status}): ${message}`);
  }

  const data: GeminiResponse = await response.json();
  const text = data.candidates?.[0]?.content?.parts?.[0]?.text;

  if (!text) {
    throw new Error('Gemini returned an empty response. Please try again.');
  }

  interface ParsedQuestion {
    topic?: string;
    question?: string;
    options?: string[];
    correctIndex?: number;
    explanation?: string;
  }

  const parsed = extractJsonFromResponse<ParsedQuestion>(text);

  if (!parsed.question || !Array.isArray(parsed.options) || parsed.options.length !== 4) {
    throw new Error('Malformed question generated by Gemini. Please try again.');
  }

  return {
    topic: parsed.topic || chosenTopic,
    questionText: parsed.question,
    options: parsed.options,
    correctIndex: typeof parsed.correctIndex === 'number' ? parsed.correctIndex : 0,
    explanation: parsed.explanation || 'No explanation provided.',
  };
}

export async function chatWithGemini(
  model: string,
  apiKey: string,
  context: Question,
  history: ChatMessage[],
  newMessage: string
): Promise<string> {
  const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`;

  const contents = history.map((msg) => ({
    role: msg.role === 'user' ? 'user' : 'model',
    parts: [{ text: msg.content }],
  }));

  contents.push({
    role: 'user',
    parts: [{ text: newMessage }],
  });

  const response = await fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      contents,
      systemInstruction: {
        parts: [{ text: getChatSystemPrompt(context) }],
      },
      generationConfig: {
        temperature: 0.7,
      },
    }),
  });

  if (!response.ok) {
    const errData = await response.json().catch(() => ({}));
    const message = (errData as GeminiResponse)?.error?.message || response.statusText;
    throw new Error(`Gemini Chat Error (${response.status}): ${message}`);
  }

  const data: GeminiResponse = await response.json();
  const text = data.candidates?.[0]?.content?.parts?.[0]?.text;

  if (!text) {
    throw new Error('Gemini returned an empty reply.');
  }

  return text;
}

export async function testGeminiKey(model: string, apiKey: string): Promise<{ success: boolean; message: string }> {
  try {
    const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`;
    const response = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        contents: [{ role: 'user', parts: [{ text: 'Hello! Respond with "OK"' }] }],
      }),
    });

    if (!response.ok) {
      const errData = await response.json().catch(() => ({}));
      const message = (errData as GeminiResponse)?.error?.message || response.statusText;
      return { success: false, message: `Failed (${response.status}): ${message}` };
    }

    return { success: true, message: 'Successfully connected to Gemini API!' };
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err);
    return { success: false, message: `Connection error: ${message}` };
  }
}
