import { Question, ChatMessage, WrongQuestionContext, Concept, ReasoningComplexity } from '../../types';
import {
  QUESTION_SYSTEM_PROMPT,
  GEMINI_QUESTION_SCHEMA,
  getQuestionPromptContext,
  getChatSystemPrompt,
  extractJsonFromResponse,
} from './prompt';
import { getConceptQuestionPrompt } from './conceptPrompt';
import { getSuggestedQuestionsForQuestion } from './suggestedQuestions';

interface GeminiResponse {
  candidates?: Array<{
    content?: {
      parts?: Array<{
        text?: string;
      }>;
    };
    finishReason?: string;
  }>;
  error?: {
    code: number;
    message: string;
    status: string;
  };
}

export async function generateGeminiQuestion(
  model: string,
  apiKey: string,
  topics: string[],
  specificTopic?: string,
  recentQuestions?: string[],
  customSubtopics?: string[],
  wrongQuestionContext?: WrongQuestionContext,
  targetConcept?: Concept,
  reasoningComplexity?: ReasoningComplexity,
  isBoss?: boolean
): Promise<Question> {
  let promptText: string;
  let defaultTopic: string;
  let defaultSubtopic: string;
  let defaultAngle: string;
  let isReinforcement = false;
  let reinforcementSourceQuestion: string | undefined = undefined;

  if (targetConcept && reasoningComplexity) {
    const conceptPrompt = getConceptQuestionPrompt(
      targetConcept,
      reasoningComplexity,
      undefined,
      recentQuestions
    );
    promptText = conceptPrompt.prompt;
    defaultTopic =
      targetConcept.topics && Object.keys(targetConcept.topics).length > 0
        ? Object.keys(targetConcept.topics)[0]
        : specificTopic || 'Physics';
    defaultSubtopic = targetConcept.canonicalName;
    defaultAngle = conceptPrompt.angle;
  } else {
    const promptContext = getQuestionPromptContext(
      topics,
      specificTopic,
      recentQuestions,
      customSubtopics,
      wrongQuestionContext
    );
    promptText = promptContext.prompt;
    defaultTopic = promptContext.topic;
    defaultSubtopic = promptContext.subtopic;
    defaultAngle = promptContext.angle;
    isReinforcement = !!promptContext.isReinforcement;
    reinforcementSourceQuestion = promptContext.reinforcementSourceQuestion;
  }

  const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`;

  const response = await fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      contents: [
        {
          role: 'user',
          parts: [{ text: promptText }],
        },
      ],
      systemInstruction: {
        parts: [{ text: QUESTION_SYSTEM_PROMPT }],
      },
      generationConfig: {
        temperature: 0.95,
        responseMimeType: 'application/json',
        responseSchema: GEMINI_QUESTION_SCHEMA,
      },
    }),
  });

  if (!response.ok) {
    const errData = await response.json().catch(() => ({}));
    const message = (errData as GeminiResponse)?.error?.message || response.statusText;
    throw new Error(`Gemini API Error (${response.status}): ${message}`);
  }

  const data: GeminiResponse = await response.json();
  const text = data.candidates?.[0]?.content?.parts?.[0]?.text;

  if (!text) {
    throw new Error('Gemini returned an empty response. Please try again.');
  }

  interface ParsedQuestion {
    topic?: string;
    subtopic?: string;
    angle?: string;
    angleFit?: string;
    question?: string;
    options?: string[];
    correctIndex?: number;
    explanation?: string;
    suggestedQuestions?: string[];
  }

  const parsed = extractJsonFromResponse<ParsedQuestion>(text);

  if (!parsed.question || !Array.isArray(parsed.options) || parsed.options.length !== 4) {
    throw new Error('Malformed question generated by Gemini. Please try again.');
  }

  const questionObj: Question = {
    topic: parsed.topic || defaultTopic,
    subtopic: parsed.subtopic || defaultSubtopic,
    angle: parsed.angle || defaultAngle,
    angleFit: parsed.angleFit || `This question explores ${defaultSubtopic} via the angle: ${defaultAngle}`,
    questionText: parsed.question,
    options: parsed.options,
    correctIndex: typeof parsed.correctIndex === 'number' ? parsed.correctIndex : 0,
    explanation: parsed.explanation || 'No explanation provided.',
    suggestedQuestions: parsed.suggestedQuestions,
    isReinforcement,
    reinforcementSourceQuestion,
    concept: targetConcept?.canonicalName,
    reasoningComplexity,
    isBossQuestion: isBoss,
  };

  questionObj.suggestedQuestions = getSuggestedQuestionsForQuestion(questionObj);
  return questionObj;
}

export async function chatWithGemini(
  model: string,
  apiKey: string,
  context: Question,
  history: ChatMessage[],
  newMessage: string
): Promise<string> {
  const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`;

  const contents = history.map((msg) => ({
    role: msg.role === 'user' ? 'user' : 'model',
    parts: [{ text: msg.content }],
  }));

  contents.push({
    role: 'user',
    parts: [{ text: newMessage }],
  });

  const response = await fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      contents,
      systemInstruction: {
        parts: [{ text: getChatSystemPrompt(context) }],
      },
      generationConfig: {
        temperature: 0.7,
      },
    }),
  });

  if (!response.ok) {
    const errData = await response.json().catch(() => ({}));
    const message = (errData as GeminiResponse)?.error?.message || response.statusText;
    throw new Error(`Gemini Chat Error (${response.status}): ${message}`);
  }

  const data: GeminiResponse = await response.json();
  const text = data.candidates?.[0]?.content?.parts?.[0]?.text;

  if (!text) {
    throw new Error('Gemini returned an empty reply.');
  }

  return text;
}

export async function testGeminiKey(model: string, apiKey: string): Promise<{ success: boolean; message: string }> {
  try {
    const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`;
    const response = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        contents: [{ role: 'user', parts: [{ text: 'Hello! Respond with "OK"' }] }],
      }),
    });

    if (!response.ok) {
      const errData = await response.json().catch(() => ({}));
      const message = (errData as GeminiResponse)?.error?.message || response.statusText;
      return { success: false, message: `Failed (${response.status}): ${message}` };
    }

    return { success: true, message: 'Successfully connected to Gemini API!' };
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err);
    return { success: false, message: `Connection error: ${message}` };
  }
}
