import { Question, ChatMessage } from '../../types';
import {
  QUESTION_SYSTEM_PROMPT,
  getQuestionUserPrompt,
  getChatSystemPrompt,
  extractJsonFromResponse,
} from './prompt';

interface OpenAIChoice {
  message?: {
    content?: string;
  };
}

interface OpenAIResponse {
  choices?: OpenAIChoice[];
  error?: {
    message: string;
    type: string;
    code: string;
  };
}

export async function generateOpenAIQuestion(
  model: string,
  apiKey: string,
  topics: string[],
  specificTopic?: string,
  recentQuestions?: string[]
): Promise<Question> {
  const chosenTopic = specificTopic || topics[Math.floor(Math.random() * topics.length)] || 'Physics';
  const userPrompt = getQuestionUserPrompt(topics, chosenTopic, recentQuestions);

  const isReasoningModel = model.startsWith('o1') || model.startsWith('o3') || model.startsWith('o4');

  const requestBody: Record<string, unknown> = {
    model: model || 'gpt-4o',
    messages: [
      { role: 'system', content: QUESTION_SYSTEM_PROMPT },
      { role: 'user', content: userPrompt },
    ],
    response_format: { type: 'json_object' },
  };

  // Standard chat models support temperature; reasoning models (o1/o3) use default reasoning effort
  if (!isReasoningModel) {
    requestBody.temperature = 0.95;
  }

  const response = await fetch('https://api.openai.com/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify(requestBody),
  });

  if (!response.ok) {
    const errData = await response.json().catch(() => ({}));
    const message = (errData as OpenAIResponse)?.error?.message || response.statusText;
    throw new Error(`OpenAI API Error (${response.status}): ${message}`);
  }

  const data: OpenAIResponse = await response.json();
  const text = data.choices?.[0]?.message?.content;

  if (!text) {
    throw new Error('OpenAI returned an empty response. Please try again.');
  }

  interface ParsedQuestion {
    topic?: string;
    question?: string;
    options?: string[];
    correctIndex?: number;
    explanation?: string;
  }

  const parsed = extractJsonFromResponse<ParsedQuestion>(text);

  if (!parsed.question || !Array.isArray(parsed.options) || parsed.options.length !== 4) {
    throw new Error('Malformed question generated by OpenAI. Please try again.');
  }

  return {
    topic: parsed.topic || chosenTopic,
    questionText: parsed.question,
    options: parsed.options,
    correctIndex: typeof parsed.correctIndex === 'number' ? parsed.correctIndex : 0,
    explanation: parsed.explanation || 'No explanation provided.',
  };
}

export async function chatWithOpenAI(
  model: string,
  apiKey: string,
  context: Question,
  history: ChatMessage[],
  newMessage: string
): Promise<string> {
  const messages = [
    { role: 'system', content: getChatSystemPrompt(context) },
    ...history.map((msg) => ({
      role: msg.role === 'user' ? 'user' : 'assistant',
      content: msg.content,
    })),
    { role: 'user', content: newMessage },
  ];

  const response = await fetch('https://api.openai.com/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      model: model || 'gpt-4o',
      messages,
      temperature: 0.7,
    }),
  });

  if (!response.ok) {
    const errData = await response.json().catch(() => ({}));
    const message = (errData as OpenAIResponse)?.error?.message || response.statusText;
    throw new Error(`OpenAI Chat Error (${response.status}): ${message}`);
  }

  const data: OpenAIResponse = await response.json();
  const text = data.choices?.[0]?.message?.content;

  if (!text) {
    throw new Error('OpenAI returned an empty reply.');
  }

  return text;
}

export async function testOpenAIKey(model: string, apiKey: string): Promise<{ success: boolean; message: string }> {
  try {
    const response = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model: model || 'gpt-4o-mini',
        messages: [{ role: 'user', content: 'Ping! Reply with "OK".' }],
        max_tokens: 10,
      }),
    });

    if (!response.ok) {
      const errData = await response.json().catch(() => ({}));
      const message = (errData as OpenAIResponse)?.error?.message || response.statusText;
      return { success: false, message: `Failed (${response.status}): ${message}` };
    }

    return { success: true, message: 'Successfully connected to OpenAI API!' };
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err);
    return { success: false, message: `Connection error: ${message}` };
  }
}
