-- Every new answer earns at least one Resource after penalties and rounding.
-- Existing receipts retain their frozen amounts; collection stays idempotent.
-- BEGIN TUNING (generated by scripts/sync-learning-tuning.mjs)
CREATE OR REPLACE FUNCTION public.learning_value_tuning() RETURNS jsonb
LANGUAGE sql IMMUTABLE SET search_path='' AS $$ SELECT '{"version":"learning-value-v2","base":20,"incorrect":0.2,"reasoning":{"directInference":1,"composition":1.15,"discrimination":1.2,"transfer":1.3,"counterfactual":1.4,"synthesis":1.55,"derivation":1.75},"firstSuccess":1.25,"masteredPractice":0.3,"dueReview":1.2,"boss":4,"minimum":1,"maximum":175,"lowValueMaximum":10,"lowValueFactors":[1,0.5,0.25],"axisSuccessLimit":3,"reviewDays":[1,3,7,14,30]}'::jsonb $$;
-- END TUNING
