-- Step 4 requires step 3's immutable receipts and Hamilton allocator.
-- No historical event is rewritten or credited by this migration.
ALTER TABLE public.learning_reward_events DROP CONSTRAINT learning_reward_events_tokens_check;
ALTER TABLE public.learning_reward_events ADD CONSTRAINT learning_reward_events_tokens_check CHECK (tokens >= 0);
-- BEGIN TUNING (generated by scripts/sync-learning-tuning.mjs)
CREATE FUNCTION public.learning_value_tuning() RETURNS jsonb
LANGUAGE sql IMMUTABLE SET search_path='' AS $$ SELECT '{"version":"learning-value-v1","base":20,"incorrect":0.2,"reasoning":{"directInference":1,"composition":1.15,"discrimination":1.2,"transfer":1.3,"counterfactual":1.4,"synthesis":1.55,"derivation":1.75},"firstSuccess":1.25,"masteredPractice":0.3,"dueReview":1.2,"boss":4,"minimum":0,"maximum":175,"lowValueMaximum":10,"lowValueFactors":[1,0.5,0.25],"axisSuccessLimit":3,"reviewDays":[1,3,7,14,30]}'::jsonb $$;
-- END TUNING

ALTER TABLE public.concepts
  ADD COLUMN reward_attempts integer NOT NULL DEFAULT 0,
  ADD COLUMN reward_successes integer NOT NULL DEFAULT 0,
  ADD COLUMN last_attempt_at timestamptz,
  ADD COLUMN last_success_at timestamptz,
  ADD COLUMN next_due_at timestamptz,
  ADD COLUMN review_step integer NOT NULL DEFAULT 0;
-- Old tracks establish prior success only for earned, non-atomic progress.
-- Do not invent a last success or a due date from last_asked.
UPDATE public.concepts SET reward_successes=1
WHERE NOT is_atomic AND (mastery<>'unseen' OR EXISTS
  (SELECT 1 FROM jsonb_each_text(reasoning_track) t WHERE t.value::integer>0));

CREATE TABLE public.learning_reward_budget (
  user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  generation bigint NOT NULL,
  day date NOT NULL,
  attempts integer NOT NULL DEFAULT 0 CHECK (attempts>=0)
);
ALTER TABLE public.learning_reward_budget ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.learning_reward_budget FROM PUBLIC,anon,authenticated,service_role;

CREATE FUNCTION public.learning_value_score(p_correct boolean,p_input jsonb) RETURNS jsonb
LANGUAGE plpgsql IMMUTABLE SET search_path='' AS $$
DECLARE t jsonb:=public.learning_value_tuning(); known boolean; first_success boolean; due boolean;
  practice boolean; low_value boolean; factors jsonb; raw numeric; capped numeric; total integer;
BEGIN
  known:=(p_input->>'metadataKnown')::boolean AND t->'reasoning' ? (p_input->>'reasoning');
  first_success:=known AND NOT (p_input->>'atomic')::boolean AND p_correct AND (p_input->>'successes')::integer=0;
  due:=known AND NOT (p_input->>'atomic')::boolean AND (p_input->>'successes')::integer>0
    AND COALESCE((p_input->>'nextDueAt')::timestamptz<=(p_input->>'answeredAt')::timestamptz,false);
  practice:=NOT known OR (p_input->>'atomic')::boolean OR (NOT due AND
    (p_input->>'preMastery'='mastered' OR (p_input->>'axisSuccesses')::integer>=(t->>'axisSuccessLimit')::integer));
  low_value:=NOT p_correct OR practice;
  factors:=jsonb_build_object(
    'correctness',CASE WHEN p_correct THEN 1 ELSE (t->>'incorrect')::numeric END,
    'reasoning',CASE WHEN known THEN (t->'reasoning'->>(p_input->>'reasoning'))::numeric ELSE 1 END,
    'novelty',CASE WHEN first_success THEN (t->>'firstSuccess')::numeric ELSE 1 END,
    'practice',CASE WHEN practice THEN (t->>'masteredPractice')::numeric ELSE 1 END,
    'review',CASE WHEN due THEN (t->>'dueReview')::numeric ELSE 1 END,
    'boss',CASE WHEN known AND NOT (p_input->>'atomic')::boolean AND (p_input->>'boss')::boolean AND p_correct THEN (t->>'boss')::numeric ELSE 1 END,
    'repetition',CASE WHEN low_value THEN COALESCE((t->'lowValueFactors'->>(p_input->>'lowValueAttempts')::integer)::numeric,0) ELSE 1 END);
  raw:=(t->>'base')::numeric*(factors->>'correctness')::numeric*(factors->>'reasoning')::numeric
    *(factors->>'novelty')::numeric*(factors->>'practice')::numeric*(factors->>'review')::numeric*(factors->>'boss')::numeric;
  capped:=LEAST(raw,(t->>CASE WHEN low_value THEN 'lowValueMaximum' ELSE 'maximum' END)::numeric)*(factors->>'repetition')::numeric;
  total:=GREATEST((t->>'minimum')::integer,LEAST((t->>'maximum')::integer,round(capped)::integer));
  RETURN jsonb_build_object('total',total,'calculation',jsonb_build_object('version',t->>'version','inputs',p_input,
    'limits',jsonb_build_object('minimum',t->'minimum','maximum',t->'maximum','lowValueMaximum',t->'lowValueMaximum','lowValueFactors',t->'lowValueFactors'),
    'base',t->'base','firstSuccess',first_success,'due',due,'lowValue',low_value,'factors',factors,
    'raw',raw,'capped',capped,'rounding','nearest-half-up'));
END $$;

-- Keep the existing mastery rules; mutate only the exact canonical identity locked by the answer transaction.
CREATE OR REPLACE FUNCTION public.score_question_internal(
  p_user_id UUID,
  p_question_id UUID,
  p_selected_index INTEGER
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  q public.questions%ROWTYPE;
  s public.game_stats%ROWTYPE;
  v_is_correct BOOLEAN;
  next_track JSONB;
  next_mastery TEXT;
  core_sum INTEGER;
  advanced_sum INTEGER;
BEGIN
  IF p_selected_index NOT BETWEEN 0 AND 3 THEN
    RAISE EXCEPTION 'selected_index must be between 0 and 3';
  END IF;

  SELECT * INTO q
  FROM public.questions
  WHERE id = p_question_id AND user_id = p_user_id
  FOR UPDATE;

  IF NOT FOUND THEN RAISE EXCEPTION 'Question not found'; END IF;
  IF q.answered_at IS NOT NULL THEN RAISE EXCEPTION 'Question has already been answered'; END IF;
  IF q.expires_at IS NOT NULL AND q.expires_at < now() THEN RAISE EXCEPTION 'Question has expired'; END IF;

  v_is_correct := p_selected_index = q.correct_index;
  UPDATE public.questions
  SET selected_index = p_selected_index, is_correct = v_is_correct, answered_at = now()
  WHERE id = q.id;

  INSERT INTO public.game_stats (user_id) VALUES (p_user_id)
  ON CONFLICT (user_id) DO NOTHING;

  UPDATE public.game_stats
  SET day_stamp = CURRENT_DATE, answers_today = 0, correct_today = 0, daily_claimed = false
  WHERE user_id = p_user_id AND day_stamp <> CURRENT_DATE;

  -- Compatibility activity counters only; legacy financial balances are frozen.
  UPDATE public.game_stats
  SET answers_today = answers_today + 1,
      correct_today = correct_today + CASE WHEN v_is_correct THEN 1 ELSE 0 END,
      castle_xp = LEAST(100, castle_xp + CASE WHEN v_is_correct THEN 8 ELSE 2 END),
      war_pressure = LEAST(94, war_pressure + CASE WHEN v_is_correct THEN 2 ELSE 0.5 END),
      updated_at = now()
  WHERE user_id = p_user_id
  RETURNING * INTO s;

  IF q.concept IS NOT NULL THEN
    INSERT INTO public.concepts (
      user_id, canonical_name, definition, aliases, topics, prerequisites,
      mastery, reasoning_track, is_atomic
    ) VALUES (
      p_user_id, q.concept, COALESCE(q.concept_definition, q.explanation), '[]'::jsonb,
      q.topic_weights, q.required_concepts, 'unseen',
      '{"directInference":0,"composition":0,"discrimination":0,"transfer":0,"counterfactual":0,"synthesis":0,"derivation":0}'::jsonb,
      false
    ) ON CONFLICT (user_id, canonical_name) DO NOTHING;
  END IF;

  IF v_is_correct AND q.concept IS NOT NULL AND q.reasoning_complexity IS NOT NULL THEN
    SELECT reasoning_track INTO next_track FROM public.concepts
    WHERE user_id = p_user_id AND canonical_name = q.concept
    FOR UPDATE;

    IF FOUND THEN
      next_track := jsonb_set(next_track, ARRAY[q.reasoning_complexity],
        to_jsonb(COALESCE((next_track ->> q.reasoning_complexity)::INTEGER, 0) + 1));
      core_sum := COALESCE((next_track ->> 'directInference')::INTEGER, 0)
        + COALESCE((next_track ->> 'composition')::INTEGER, 0)
        + COALESCE((next_track ->> 'discrimination')::INTEGER, 0);
      advanced_sum := COALESCE((next_track ->> 'transfer')::INTEGER, 0)
        + COALESCE((next_track ->> 'synthesis')::INTEGER, 0)
        + COALESCE((next_track ->> 'derivation')::INTEGER, 0);
      next_mastery := CASE
        WHEN (SELECT bool_and(COALESCE((next_track ->> item.key)::INTEGER, 0) >= 3)
              FROM unnest(ARRAY['directInference','composition','discrimination','transfer','counterfactual','synthesis','derivation']) AS item(key)) THEN 'mastered'
        WHEN COALESCE((next_track ->> 'directInference')::INTEGER, 0) >= 1
          AND COALESCE((next_track ->> 'composition')::INTEGER, 0) >= 1
          AND COALESCE((next_track ->> 'discrimination')::INTEGER, 0) >= 1
          AND core_sum >= 5 AND advanced_sum >= 3 THEN 'proficient'
        ELSE 'learning' END;
      UPDATE public.concepts SET reasoning_track = next_track, mastery = next_mastery,
        last_asked = now(), updated_at = now()
      WHERE user_id = p_user_id AND canonical_name = q.concept;
    END IF;
  END IF;

  RETURN jsonb_build_object(
    'question', to_jsonb(q) || jsonb_build_object('selected_index', p_selected_index, 'is_correct', v_is_correct, 'answered_at', now()),
    'stats', to_jsonb(s)
  );
END;
$$;


CREATE OR REPLACE FUNCTION public.record_question_answer(p_user_id uuid,p_question_id uuid,p_selected_index integer) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE k public.kingdom_state%ROWTYPE; q public.questions%ROWTYPE; c public.concepts;
  previous public.learning_reward_events%ROWTYPE; budget public.learning_reward_budget%ROWTYPE;
  result jsonb; score jsonb; breakdown jsonb; input jsonb; t jsonb:=public.learning_value_tuning();
  answer_time timestamptz; correct boolean; known boolean; atomic boolean; successes integer; step integer; due boolean;
BEGIN
  IF p_selected_index IS NULL OR p_selected_index NOT BETWEEN 0 AND 3 THEN RAISE EXCEPTION 'Invalid answer.'; END IF;
  -- Lock order is shared with generation, collection, spending and reset.
  SELECT * INTO STRICT k FROM public.kingdom_state WHERE user_id=p_user_id FOR UPDATE;
  SELECT * INTO q FROM public.questions WHERE id=p_question_id AND user_id=p_user_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Question not found'; END IF;
  IF NOT q.trusted_issuance OR q.generation IS DISTINCT FROM k.generation OR q.expires_at IS NULL OR NOT q.prerequisites_met THEN
    RAISE EXCEPTION 'Question has expired';
  END IF;
  SELECT * INTO previous FROM public.learning_reward_events WHERE user_id=p_user_id AND question_id=p_question_id FOR UPDATE;
  IF FOUND THEN
    IF previous.selected_index<>p_selected_index THEN RAISE EXCEPTION 'Question has already been answered with a different selection'; END IF;
    RETURN jsonb_build_object('question',to_jsonb(q)||jsonb_build_object('reward',previous.reward),
      'stats',(SELECT to_jsonb(s) FROM public.game_stats s WHERE user_id=p_user_id),
      'collected',previous.collected_at IS NOT NULL,'reward',previous.reward,'kingdom',public.kingdom_snapshot(p_user_id));
  END IF;
  answer_time:=clock_timestamp();
  IF q.expires_at<=answer_time THEN RAISE EXCEPTION 'Question has expired'; END IF;
  IF public.pending_learning_reward(p_user_id) IS NOT NULL THEN RAISE EXCEPTION 'Collect your Resources before answering another question.'; END IF;
  c:=public.resolve_reward_concept(p_user_id,q.concept);
  IF c.id IS NOT NULL THEN SELECT * INTO c FROM public.concepts WHERE id=c.id FOR UPDATE; END IF;
  -- Issued name + definition can establish a new target. Missing metadata earns only capped conservative practice.
  known:=(c.id IS NOT NULL OR (NULLIF(trim(q.concept),'') IS NOT NULL AND NULLIF(trim(q.concept_definition),'') IS NOT NULL))
    AND t->'reasoning' ? q.reasoning_complexity;
  known:=COALESCE(known,false);
  atomic:=COALESCE(c.is_atomic,false);
  successes:=GREATEST(COALESCE(c.reward_successes,0),CASE WHEN NOT atomic AND c.id IS NOT NULL AND
    (c.mastery<>'unseen' OR EXISTS (SELECT 1 FROM jsonb_each_text(c.reasoning_track) v WHERE v.value::integer>0)) THEN 1 ELSE 0 END);
  correct:=p_selected_index=q.correct_index;
  INSERT INTO public.learning_reward_budget(user_id,generation,day) VALUES(p_user_id,k.generation,(answer_time AT TIME ZONE 'UTC')::date)
    ON CONFLICT(user_id) DO NOTHING;
  SELECT * INTO STRICT budget FROM public.learning_reward_budget WHERE user_id=p_user_id FOR UPDATE;
  IF budget.generation<>k.generation OR budget.day<>(answer_time AT TIME ZONE 'UTC')::date THEN
    budget.attempts:=0;
    UPDATE public.learning_reward_budget SET generation=k.generation,day=(answer_time AT TIME ZONE 'UTC')::date,attempts=0 WHERE user_id=p_user_id;
  END IF;
  input:=jsonb_build_object('canonicalConcept',COALESCE(c.canonical_name,q.concept),'metadataKnown',known,
    'preMastery',COALESCE(c.mastery,'unseen'),'atomic',atomic,'successes',successes,
    'axisSuccesses',COALESCE((c.reasoning_track->>q.reasoning_complexity)::integer,0),
    'nextDueAt',c.next_due_at,'reasoning',COALESCE(q.reasoning_complexity,''),'boss',COALESCE(q.is_boss_question,false),
    'lowValueAttempts',budget.attempts,'answeredAt',answer_time);
  score:=public.learning_value_score(correct,input);
  breakdown:=public.castle_learning_reward(q.id,correct,(score->>'total')::integer,q.topic_weights,q.topic)
    ||jsonb_build_object('calculation',score->'calculation');
  -- Canonicalize legacy alias issuances before the unchanged mastery scorer runs.
  IF c.id IS NOT NULL AND q.concept IS DISTINCT FROM c.canonical_name THEN
    UPDATE public.questions SET concept=c.canonical_name WHERE id=q.id;
  END IF;
  result:=public.score_question_internal(p_user_id,p_question_id,p_selected_index);
  c:=public.resolve_reward_concept(p_user_id,COALESCE(c.canonical_name,q.concept));
  IF c.id IS NOT NULL THEN
    step:=c.review_step;
    due:=(score->'calculation'->>'due')::boolean;
    IF atomic OR NOT known THEN c.next_due_at:=NULL; step:=0;
    ELSIF NOT correct THEN
      step:=0;
      c.next_due_at:=CASE WHEN successes>0 THEN answer_time+make_interval(days=>(t->'reviewDays'->>0)::integer) ELSE NULL END;
    ELSIF successes=0 OR c.next_due_at IS NULL OR due THEN
      step:=CASE WHEN due THEN LEAST(step+1,jsonb_array_length(t->'reviewDays')-1) ELSE 0 END;
      c.next_due_at:=answer_time+make_interval(days=>(t->'reviewDays'->>step)::integer);
    END IF;
    UPDATE public.concepts SET reward_attempts=reward_attempts+1,
      reward_successes=successes+CASE WHEN correct AND NOT atomic THEN 1 ELSE 0 END,
      last_attempt_at=answer_time,last_success_at=CASE WHEN correct AND NOT atomic THEN answer_time ELSE last_success_at END,
      next_due_at=c.next_due_at,review_step=step,
      mastery=CASE WHEN atomic THEN 'mastered' ELSE mastery END WHERE id=c.id;
  END IF;
  IF (score->'calculation'->>'lowValue')::boolean THEN
    UPDATE public.learning_reward_budget SET attempts=LEAST(attempts+1,jsonb_array_length(t->'lowValueFactors')) WHERE user_id=p_user_id;
  END IF;
  INSERT INTO public.learning_reward_events(user_id,question_id,generation,selected_index,topic,tokens,reward)
    VALUES(p_user_id,q.id,k.generation,p_selected_index,q.topic,(score->>'total')::integer,breakdown);
  RETURN result||jsonb_build_object('question',result->'question'||jsonb_build_object('reward',breakdown),
    'reward',breakdown,'collected',false,'kingdom',public.kingdom_snapshot(p_user_id));
END $$;

REVOKE ALL ON FUNCTION public.learning_value_tuning(),public.learning_value_score(boolean,jsonb) FROM PUBLIC,anon,authenticated,service_role;
